spring:
  datasource:
    url: jdbc:h2:mem:dreamcup
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    add-properties: true
