spring:
  datasource:
    url: jdbc:h2:mem:dreamcup
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    add-properties: true

  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

logging:
  level:
    com.dreamcup: debug

jwt:
  header: Authorization
  # echo 'ej-jwt-secret-ej-jwt-secret-ej-jwt-secret-ej-jwt-secret-ej-jwt-secret-ej-jwt-secret-ej-jwt-secret'|base64
  secret: ZWotand0LXNlY3JldC1lai1qd3Qtc2VjcmV0LWVqLWp3dC1zZWNyZXQtZWotand0LXNlY3JldC1lai1qd3Qtc2VjcmV0LWVqLWp3dC1zZWNyZXQtZWotand0LXNlY3JldA==
  token-validity-in-seconds: 86400
