spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:dreamcup
    username: sa
    password:
    driver-class-name: org.h2.Driver

  output.ansi: enabled=always
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    add-properties: true
